sudo: false
language: d
d:
- dmd
- ldc
os:
- linux
- osx

script:
- dub test --compiler=${DC} --coverage

after_success:
- dub run
- cp doveralls doveralls_${TRAVIS_OS_NAME}_travis

deploy:
  provider: releases
  api_key:
    secure: grXb93P/CfPqwT29lpS4dX2ZmzEUEB7hxd+GXlVUq30rp3NIS3sYJcKsZvTEompqfuSnkxK0mAD8uYqjioQoAE2/dhbO62FBDrGshBtXV/DgnEc3SiO1vz7dxTqLiblZq5xd7kf4PuN3fVSXTG9t2ADWAfsj/fZIq86VnHbHpJk=
  file: doveralls_${TRAVIS_OS_NAME}_travis
  skip_cleanup: true
  on:
    repo: ColdenCullen/doveralls
    tags: true
    condition: ${DC} = ldc2
