sudo: false
language: d
d:
- dmd
- ldc
os:
- linux
- osx

script:
- dub test --compiler=${DC} --coverage

after_success:
- dub run
- cp doveralls doveralls_${TRAVIS_OS_NAME}_travis

deploy:
  provider: releases
  api_key:
    secure: Zsj3klFEJYlKlZNO4isZwZ11qOt7HCHMvPe5kECuFJ5mP+1wOkWj1V4U/7TXwep9Sv310Jh5T0lUFvkPTl30dFiUYbsIXYtwWRZNfuih+FZgos/YkA+H9SQZy+Jt1mUbWMF/s3f7ogFvdh+rl61hSnDMUDImS3IXuc01FPrWsVk=
  file: doveralls_${TRAVIS_OS_NAME}_travis
  skip_cleanup: true
  on:
    repo: ColdenCullen/doveralls
    tags: true
    condition: ${DC} = ldc2
